---
- name: Manage ZFS installation on Fedora
  hosts: all
  become: yes
  tasks:
    - name: Remove zfs-fuse package
      ansible.builtin.yum:
        name: zfs-fuse
        state: absent
        allow_erasing: yes

    - name: Install ZFS repository
      ansible.builtin.yum:
        name: https://zfsonlinux.org/fedora/zfs-release-2-5{{ ansible_distribution_version | regex_replace('^([^0-9]+)', '') }}.noarch.rpm
        state: present

    - name: Install kernel-devel package
      ansible.builtin.yum:
        name: kernel-devel
        state: present

    - name: Install ZFS package
      ansible.builtin.yum:
        name: zfs
        state: present

    - name: Load ZFS module
      ansible.builtin.shell: modprobe zfs

    - name: Ensure ZFS module is loaded on boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/zfs.conf
        content: zfs
        mode: '0644'

    - name: Protect ZFS from being removed by dnf
      ansible.builtin.copy:
        dest: /etc/dnf/protected.d/zfs.conf
        content: zfs
        mode: '0644'

    - name: Download 45Drives setup script
      ansible.builtin.get_url:
        url: https://repo.45drives.com/setup
        dest: /tmp/45drives-setup.sh
        mode: '0755'
      
    - name: Run 45Drives setup script
      ansible.builtin.shell: bash /tmp/45drives-setup.sh
      args:
        warn: false

    - name: Remove 45Drives setup script
      ansible.builtin.file:
        path: /tmp/45drives-setup.sh
        state: absent

    - name: Install some packages
      ansible.builtin.dnf:
        name:
          - git
          - neovim
          - python3-jinja2
          - glances
          - virtiofsd
          - postfix
          - cyrus-sasl-plain
        state: present
