---
- name: Setup Postfix
  hosts: all
  become: yes
  vars:
    smtp_password: "YOUR_SMTP_PASSWORD"  # Replace with your actual password or set it using Ansible vault
  tasks:
    - name: Configure Postfix main.cf
      copy:
        dest: /etc/postfix/main.cf
        content: |
          relayhost = [smtp.protonmail.ch]:587
          smtp_sasl_auth_enable = yes
          smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
          smtp_sasl_security_options = noanonymous
          smtp_tls_security_level = encrypt
          smtp_tls_CAfile = /etc/ssl/certs/ca-bundle.crt
          smtp_sasl_tls_security_options = noanonymous
          sender_canonical_maps = hash:/etc/postfix/sender_canonical
          smtp_generic_maps = hash:/etc/postfix/generic
          virtual_alias_maps = hash:/etc/postfix/virtual

    - name: Configure /etc/postfix/sender_canonical
      copy:
        dest: /etc/postfix/sender_canonical
        content: |
          /.+/    admin@schnelle.dev

    - name: Configure /etc/postfix/generic
      copy:
        dest: /etc/postfix/generic
        content: |
          @odin.local    admin@schnelle.dev

    - name: Configure /etc/postfix/virtual
      copy:
        dest: /etc/postfix/virtual
        content: |
          @odin.local nikki@schnelle.dev

    - name: Configure /etc/postfix/sasl_passwd
      copy:
        dest: /etc/postfix/sasl_passwd
        content: |
          [smtp.protonmail.ch]:587    admin@schnelle.dev:{{ smtp_password }}
        mode: '0600'

    - name: Set permissions for Postfix files
      file:
        path: "{{ item }}"
        mode: '0600'
      loop:
        - /etc/postfix/sasl_passwd
        - /etc/postfix/virtual
        - /etc/postfix/generic
        - /etc/postfix/sender_canonical

    - name: Run postmap on Postfix files
      command: "postmap {{ item }}"
      loop:
        - /etc/postfix/sasl_passwd
        - /etc/postfix/virtual
        - /etc/postfix/generic
        - /etc/postfix/sender_canonical

    - name: Reload Postfix
      systemd:
        name: postfix
        state: reloaded

    - name: Restart Postfix
      systemd:
        name: postfix
        state: restarted

    - name: Test email configuration
      shell: echo "Setting up email was successful using ansible" | mail -s "Test Email" root
