---
---
- name: Configure custom SSH settings
  hosts: all
  become: yes

  vars:
    authorized_keys_content: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG+r1Gqwxstxou7BUXz1MIi8mKB8dLeMKDPgVOhTW4Ak nikki@schnelle.dev

  tasks:
    - name: Ensure shared_ssh_key group exists
      group:
        name: shared_ssh_key
        state: present

    - name: Ensure /etc/ssh/sshd_config.d directory exists
      file:
        path: /etc/ssh/sshd_config.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create custom SSH config
      copy:
        dest: /etc/ssh/sshd_config.d/99-nikki.conf
        content: |
          PasswordAuthentication no
          PermitRootLogin no
          Match Group shared_ssh_key
              AuthorizedKeysFile /etc/ssh/common_authorized_keys
        owner: root
        group: root
        mode: '0644'

    - name: Ensure the authorized keys file exists with specific content
      copy:
        dest: /etc/ssh/common_authorized_keys
        content: "{{ authorized_keys_content }}"
        owner: root
        group: shared_ssh_key
        mode: '0640'

    - name: Reload SSHD service
      systemd:
        name: sshd
        state: reloaded


- name: Create users with specified IDs, home directories, and shell
  hosts: all
  become: yes

  vars:
    users:
      - { name: "pihole", uid: 3001, home: "/Gungnir/apps/pihole" }
      - { name: "reverseproxy", uid: 3002, home: "/Gungnir/apps/reverseproxy" }
      - { name: "jellyfin", uid: 3003, home: "/Gungnir/apps/jellyfin" }
      - { name: "paperless", uid: 3004, home: "/Gungnir/apps/paperless" }
      - { name: "staticpages", uid: 3005, home: "/Gungnir/apps/staticpages" }
      - { name: "uptime", uid: 3006, home: "/Gungnir/apps/uptime" }
      - { name: "wiki", uid: 3007, home: "/Gungnir/apps/wiki" }
      - { name: "vaultwarden", uid: 3008, home: "/Gungnir/apps/vaultwarden" }
      - { name: "nextcloud", uid: 3009, home: "/Gungnir/apps/nextcloud" }
      - { name: "auth", uid: 3010, home: "/Gungnir/apps/auth" }
      - { name: "homeassistant", uid: 3011, home: "/Gungnir/apps/homeassistant" }
      - { name: "backup", uid: 3012, home: "/home/backup" }
      - { name: "nextcloud-aio", uid: 3013, home: "/Gungnir/apps/nextcloud-aio" }
      - { name: "netboot", uid: 3014, home: "/Gungnir/apps/netboot" }
      - { name: "ai", uid: 3015, home: "/Gungnir/apps/ai" }
      - { name: "photos", uid: 3016, home: "/Gungnir/apps/photos" }
      - { name: "syncthing", uid: 3017, home: "/Gungnir/apps/syncthing" }

  tasks:
    - name: Ensure shared_ssh_key group exists
      group:
        name: shared_ssh_key
        state: present

    - name: Create users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        home: "{{ item.home }}"
        shell: /bin/zsh
        group: shared_ssh_key
        state: present
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Ensure home directories exist and have correct permissions
      file:
        path: "{{ item.home }}"
        state: directory
        owner: "{{ item.name }}"
        group: shared_ssh_key
        mode: '0755'
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.name }}"
