---
- name: Configure custom SSH settings
  hosts: all
  become: yes
  vars_files: 
    - vars.yml

  tasks:
    - name: Ensure shared_ssh_key group exists
      group:
        name: shared_ssh_key
        state: present

    - name: Ensure /etc/ssh/sshd_config.d directory exists
      file:
        path: /etc/ssh/sshd_config.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create custom SSH config
      copy:
        dest: /etc/ssh/sshd_config.d/99-shared_ssh_key.conf
        content: |
          PasswordAuthentication no
          PermitRootLogin no
          Match Group shared_ssh_key
              AuthorizedKeysFile /etc/ssh/common_authorized_key
        owner: root
        group: root
        mode: '0644'

    - name: Ensure the authorized keys file exists with specific content
      copy:
        dest: /etc/ssh/common_authorized_key
        content: "{{ common_user_ssh_key }}"
        owner: root
        group: shared_ssh_key
        mode: '0644'

    - name: Reload SSHD service
      systemd:
        name: sshd
        state: reloaded
